### ISSUE TITLE
White background not so white

### ISSUE THREAD

**Issue by cparu** [OpenHantek/OpenHantek6022#177] opened 2021-04-01 18:22 UTC
When setting the background to white (ffffffff), the background of the measure menu is fffcfcfc

**To Reproduce**
1)Set background to ffffffff (and maybe change the others colors accordingly, for example, I have:
Background: ffffffff
Grid: ff3f3f3f
Axes: ff7f7f7f
Border: ff000000
Markers: ff3f3f3f
Text: ff000000 
2)Close and reopen OpenHantek
3)Enable the measure menu
4)See that the background of the measure menu is fffcfcfc, with some ffffffff boxes

**Expected behavior**
The background of the measure menu is ffffffff.

**Screenshots**
![prob](https://user-images.githubusercontent.com/60483064/113336296-7bcced00-9326-11eb-98f0-754323381dc8.PNG)

**Computer environment (please complete the following information):**
 - OpenHantek version: release v3.2, latest stable
 - OS: Windows 10 20H2, but I am pretty sure it affects all other platforms
 - Video hardware: Mobile Ryzen 3500U Integrated Graphics

**Solution**
When the background is set to ffffffff, the background of the measure menu is also ffffffff

**Alternative solution**
Add another color setting in settings>colors, called "Measure bacground" that changes the background of the measure menu.

**Comment by Ho-Ro** [comment] 2021-04-01 19:43
This is no issue that I can solve. I checked the relevant code:
[`cursorDataGrid->setBackgroundColor( view->colors->background );`](https://github.com/OpenHantek/OpenHantek6022/blob/db23aae03e713b4890519b407d1617847b3dede0/openhantek/src/dsowidget.cpp#L184)
and this is what I get for `view->colors->background = 0xFFFFFFFF`:
`cursorDataGrid->setBackgroundColor(  QColor(ARGB 1, 1, 1, 1) );`
If I change to `view->colors->background = 0xFFFEFEFE` I see this:
`cursorDataGrid->setBackgroundColor(  QColor(ARGB 1, 0.996078, 0.996078, 0.996078) );`
This value `view->colors->background` is handed through directly and unchanged into the class `dataGrid` that is subclassed from Qt's `QGroupBox`. 
So my conclusion is that the shading effect is introduced by `QGroupBox` as an intended behaviour. Also on a black background the measure box shows a very dark grey border.
![image](https://user-images.githubusercontent.com/12542359/113345809-42e74500-9333-11eb-8a44-be1de5f1722e.png)

I will not deep dive into the original Qt code and close this issue.

**Closed by Ho-Ro** 2021-04-01 19:43 UTC
Labels: no issue
